version: 1.2
workflows:
  - subclass: WDL
    primaryDescriptorPath: /wdl/GATK-Germline-Snps-Indels-main.wdl
    testParameterFiles:
      - /exec/gatk.parallel.hg19.dev.exec.json 
      - /inputs/GATK-Germline-Snps-Indels-inputs.json
    authors:
      - orcid: 0000-0002-8906-5921
